<?php

namespace SchoolManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    
    public function getAllMentorsWhoTeachThisSubject($subject) {
        
        $mentors = $this->createQueryBuilder('m')
           // ->leftJoin('m.canTeach', 's')
            //    ->where('s =:subject')
          //  ->//setParameter('subject', $subject)
            ->getQuery()->getResult();
    
        return $mentors;
    }
    
}
